name: 打包server

on:
  push:
    branches:
      - server-prod
  workflow_dispatch:

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: executing remote ssh commands using password
        # 使用action库 action/checkout获取代码
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRIVATE_HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/ubuntu/server/cheese-server
            docker-compose up -d
